services:
  redis:
    image: redis:8-alpine
    container_name: redis-demo
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-demo-data:/data
    networks:
      - redis-tutorial

  mongo:
    image: mongo:7.0
    container_name: mongo-demo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: redis_demo
    volumes:
      - mongo-demo-data:/data/db
    networks:
      - redis-tutorial

volumes:
  redis-demo-data:
    driver: local
  mongo-demo-data:
    driver: local

networks:
  redis-tutorial:
    driver: bridge
